# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
  
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'frontEnd'
    targetPath: 'src/MyWebApp/bin/Release/netcoreapp2.0/linux-x64/publish'

  task: DownloadPipelineArtifact@0
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)

- script: |
    npm install
    npm uninstall jest
    npm run build
  displayName: 'npm install and build'
